### ISSUE TITLE
[Bug Report] Categorized Volumes in readlightnovel.org

### ISSUE THREAD

**Issue by PhantomWriterEisen** [HanaDigital/NovelScraper#36]
- Operating System [OS]: Windows 10 Home
 - 32/64bit: 64
 - App Version:1.0.4

The NovelScraper only detects 5-20 chapters when the novel has more than that, an example is Overlord (LN), https://www.readlightnovel.org/overlord-ln

**To Reproduce**
1. Go to 'NovelScraper'
2. Click on 'readlightnovel.org download'
3. Search for 'https://www.readlightnovel.org/overlord-ln'
4. See error by downloading any novels that is categorized or separated by volumes

**Expected behavior**
Download all the chapters instead of just a certain amount of chapters, it can download it but it doesn't detect the other chapters

**Screenshots**

![image](https://user-images.githubusercontent.com/67043415/84866266-0c924f00-b0ac-11ea-8f59-8eb1a05999ac.png)

What I expected it to download

![image](https://user-images.githubusercontent.com/67043415/84866297-1c119800-b0ac-11ea-88f1-003bb7d222f1.png)

**Comment by dr-nyt** [comment]
This issue is fixed in the latest release so I will close it.
