### ISSUE TITLE
[Bug Report] readlightnovel.org

### ISSUE THREAD

**Issue by MagosCawl** [HanaDigital/NovelScraper#41]
**Please complete the following information):**
Android
7.0 Xiaomi

**Describe the bug**
When using a variety of mobile epub readers (ReadEra, Lithium & Liberera), it's impossible to open or properly display the downloaded .epub for 'Mardock Scramble'. When I examine the file with Calibre on my PC, the contents are all there. Similar issues happen for 'Solo leveling'. Some other novels have issues on any given app, but switching app works fine to alleviate it. Seems 'ReadEra' is the most problematic out of these 3 with what it elects to parse and render.

Links to problematic novels
https://www.readlightnovel.org/solo-leveling 
https://www.readlightnovel.org/mardock-scramble

Results from each android epub reader
ReadEra: Pages are blank except for the 'dr-nyt' message for both Mardock Scramble & Solo Leveling
Lithium: Throws an error message about mismatch of br line. Displays some text but not all for both Mardock Scramble & Solo Leveling
Liberera: Crashes immediately for Mardock Scramble. Not tested with Solo Leveling.
Calibre (PC): Loads up just fine but not a convenient place to read a book on

**To Reproduce**
1. Download the novel
2. Transfer to android device
3. Download any of the mentioned epub apps
4. Encounter issues as described above

**Expected behavior**
For the contents to be displayed properly.

**Screenshots**
From Solo leveling in Lithium & ReadEra :
Lithium
![Solo Leveling - Lithium](https://user-images.githubusercontent.com/61636297/88311785-a2577480-cd11-11ea-8b67-453646e28488.jpg)
![Solo Leveling - Lithium 2](https://user-images.githubusercontent.com/61636297/88311783-a1264780-cd11-11ea-8a8d-3e7eb0875fba.jpg)

ReadEra 
![Solo leveling - ReadEra](https://user-images.githubusercontent.com/61636297/88311790-a4213800-cd11-11ea-9fa0-0120bcaee3f1.jpg)
![Solo leveling - ReadEra 2](https://user-images.githubusercontent.com/61636297/88311788-a388a180-cd11-11ea-87be-6aa934fe7cb5.jpg)

**Comment by dr-nyt** [comment]
Thanks for bringing up such a detailed bug report, it helps alot. I think I already have an idea on what could be the problem.

**Comment by dr-nyt** [comment]
This is odd, I can read I alone level up on both of those apps on my Samsung Note 9. Which version did you last download this file? You might be able to check the date from the metadata of the .epub file. And could you send me the .epub file through email or discord? shehryar.dev@gmail.com

**Comment by MagosCawl** [comment]
Hi,

Thanks for your reply!

I did more tests to rule out that it was device-specific or a cache issue.

**Actions taken on primary device (Xiaomi Note 4)**

- Deleted files off of device and retrieved them from original location (zipped folder on cloud storage) and copied over
- Manually removed any cached copies prior to this.
- Cleared cache of all 3 epub reader apps to ensure no residual data interfered before testing

**Results**
ReadEra: Both novels do not display anything on each chapter other than the 'dr-nyt' text
Lithium: Error message as previously shown on both novels (exact line and column varies)
![lithium](https://user-images.githubusercontent.com/61636297/88442336-65c07180-ce14-11ea-9156-deeb33d229a1.PNG)
Librera: Mardock Scramble crashes upon loading. Solo leveling can be read just fine.


I then transferred the same files to a new device, a Samsung Galaxy A 2016 model

**Results**
ReadEra: Same as above
Lithium: Same as above
Librera: Same as above

I then downloaded BlueStack and ran each application from the virtual android environment.

**Results**
ReadEra: Same as above
Lithium: Same as above
Librera: Same as above


Reading the metadata, there was nothing in Calibre that indicated which version of NovelScraper I used to download these files (something you could perhaps add for troubleshooting purposes?)

I then downloaded the books fresh via version 1.0.6 of NovelScraper and ran into the same issue again (tested via BlueStacks & primary device)

**Results**
ReadEra: Same as above
Lithium: Same as above
Librera: Same as above

I've emailed you a copy of both files as well.

Thanks for looking into this!

**Comment by dr-nyt** [comment]
This bug is now fixed in version 1.0.7
