### ISSUE TITLE
[Bug Report] Readlightnovel.org - xhtml tag mismatch causing rendering issues

### ISSUE THREAD

**Issue by MagosCawl** [HanaDigital/NovelScraper#43]
Hi,

I've tested more in 1.0.7 and the issue I previously reported in #41  is still partially ongoing (but improved compared to 1.0.6). 

Files still cannot be rendered in ReadEra but can for the most part do so in Lithium (error messages persists on individual chapters on some books). I suspect the discrepancy between ReadEra and Lithium is because ReadEra appears to load the entire .epub file in one go, whereas Lithium will load chapters individually within it. Not entirely sure though, since it's an observation based on load times. This could be why all chapters load fine in Lithium of some books, whereas, I suspect, ReadEra will have some issue with tags outside of the actual chapter contents in the epub.

I also just noticed that version 1.0.6 did not capture all chapters available on some of the stories, but it appears your fix in 1.0.7 solved this. I've thus included the chapter count for comparison too.

Here are the books I've tested with 1.0.7

A monster who levels up (https://www.readlightnovel.org/a-monster-who-levels-up)
A record of a mortal's journey to immortality (https://www.readlightnovel.org/a-record-of-a-mortals-journey-to-immortality)
ballad of the desert (https://www.readlightnovel.org/ballad-of-the-desert)
baka to test (https://www.readlightnovel.org/baka-to-test-to-shoukanjuu)
awakening (https://www.readlightnovel.org/awakening-)
coiling dragon (https://www.readlightnovel.org/coiling-dragon)
chaos of beauty (https://www.readlightnovel.org/chaos-of-beauty)
mardock scramble (https://www.readlightnovel.org/mardock-scramble)
solo leveling (https://www.readlightnovel.org/solo-leveling)

**A monster who levels up**
91 chapters downloaded in 1.0.6
174 chapters downloaded in 1.0.8
Contents cannot be rendered in ReadEra. Works fine in Lithium (manually loaded all chapters)

**A record of a mortal's journey to immortality**
480 chapters downloaded in 1.0.6
1446 chapters downloaded in 1.0.7 
Contents cannot be rendered in ReadEra. Works fine in Lithium (spot checked at random)

**ballad of the desert**
42 chapters downloaded in 1.0.6
42 chapters downloaded in 1.0.7
Contents cannot be rendered in ReadEra. Error message in Lithium, book 2 chapter 14 ("error on line 41 at column 119: Opening and ending tag mismatch: img line 0 and p

**baka to test to shoukanjuu**
17 volumes dwonloaded in 1.0.6
17 volumes dwonloaded in 1.0.7
Contents cannot be rendered in ReadEra. Error message in Lithium, book 1 chapter 1-3 (error on line 52 at column 129: Opening and ending tag mismatch: img line 0 and p"

**awakening** 
234 chapters downloaded in 1.0.6
234 chapters downloaded in 1.0.7
Contents cannot be rendered in ReadEra. Works fine in Lithium (spot checked at random).

**Chaos of beauty**
36 chapters downloaded in 1.0.6
36 chapters downloaded in 1.0.7
Contents cannot be rendered in ReadEra. Error message in Lithium, chapter 21-24 (error on line 52 at column 129: Opening and ending tag mismatch: img line 0 and p"

**mardock scramble**
12 chapters downloaded in 1.0.6
12 chapters downloaded in 1.0.7
Contents cannot be rendered in ReadEra. Works fine in Lithium (manually checked all chapters)

**Solo leveling**
270 chapters downloaded in 1.0.6
270 chapters downloaded in 1.0.7
Contents cannot be rendered in ReadEra. Works fine in Lithium (spot checked at random)

**Comment by dr-nyt** [comment]
Yea, this is the result of the websites writing bad html, some readers can correct it automatically while some don't. I'll check if I can make something that finds all these errors and correct them before adding them to an epub.

**Comment by dr-nyt** [comment]
Just pushed version 1.0.8, lithium works fine now, but ReadEra still has problems and doesn't say what its problems are, so I don't know what to do with that.

**Comment by MagosCawl** [comment]
Thank you so much for your help. The issue is resolved :)  I'll use Lithium for stuff from RLN going forward.
