### ISSUE TITLE
https://www.readlightnovel.org/the-desolate-era 

### ISSUE THREAD

**Issue by songoku642** [HanaDigital/NovelScraper#57]
Trying to download my favorite novel, after an hour and progress of 5% it just stops. Can u add the option of resuming downloads?

**Comment by dr-nyt** [comment]
I'll look into this and get back to you soon

**Comment by dr-nyt** [comment]
I will follow up with you on your other duplicate [issue](https://github.com/HanaDigital/NovelScraper/issues/58)
