### ISSUE TITLE
Download progress lost on network issue

### ISSUE THREAD

**Issue by songoku642** [HanaDigital/NovelScraper#58]
https://www.readlightnovel.org/the-desolate-era download stops at 5%

**Comment by dr-nyt** [comment]
There seems to be an issue with either loading the chapters or connection timing out. In the meantime, you can download this novel from another source, like from the `NovelFull` source by searching for `desolate era` in the search box

**Comment by dr-nyt** [comment]
This was fixed in version 2.0.5
